apiVersion: v1
kind: Service
metadata:
  name: devboard-frontend-service
  namespace: devboard
spec:
  type: NodePort # Use LoadBalancer if you are on AWS/GCP, or ClusterIP for internal only
  selector:
    app: devboard-frontend
  ports:
    - protocol: TCP
      port: 30080      # The port you want to expose outside
      targetPort: 4173 # The port your frontend container is listening on

